server:
  port: 9996
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
      username: root
      password: root
#mybatis配置文件
mybatis:
  mapper-locations: classpath:mapper/*.xml